<?php

namespace CG\CuddleBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function get($id)
    {
        return $this->createQueryBuilder('c')
            ->where('c.id = :id')
            ->setParameter('id', $id)
            ->leftJoin('c.cuddles', 'cud')
            ->addSelect('cud')
            ->getQuery()
            ->getOneOrNullResult()
        ;
    }
}
