<?php

namespace CG\CuddleBundle\Repository;
use CG\UserBundle\Entity\User;

/**
 * CuddleUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CuddleUserRepository extends \Doctrine\ORM\EntityRepository
{
    public function getReceivedCuddles(User $user)
    {
        return $this->createQueryBuilder('cu')
            ->join('cu.cuddle', 'c')
            ->addSelect('c')
            ->join('c.category', 'cat')
            ->addSelect('cat')
            ->where('cu.user = :user')
            ->setParameter('user', $user)
            ->orderBy('cu.date', 'desc')
            ->getQuery()
            ->getResult()
        ;
    }

    public function getDQLReceivedCuddles(User $user)
    {
        return $this->createQueryBuilder('cu')
            ->join('cu.cuddle', 'c')
            ->addSelect('c')
            ->where('cu.user = :user')
            ->setParameter('user', $user)
            ->getDQL()
        ;
    }
}
