<?php

namespace CG\CuddleBundle\Repository;

/**
 * CuddleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CuddleRepository extends \Doctrine\ORM\EntityRepository
{
}
